POST http://localhost:80/member
Content-Type: application/json

{
  "memail" : "qweqwe@qweqwe.com" ,
  "mpassword" : "123123" ,
  "mname" : "강호동" ,
  "mphone" : "010-1234-1234"
}

###
# get
GET http://localhost:80/member?mno=1

PUT



# DELETE
DELETE http://localhost:80/member

# PUT
PUT http://localhost:80/member